// =============================================================================
// Angsana Exchange — Event Publisher (publisher-lite)
//
// Implements the Angsana Event Publisher Pattern v0.1 (in-tree mirror at
// docs/architecture/Angsana_Event_Publisher_Pattern_v0_1.md). This is the
// single re-point site for event emission from Exchange. Today the body
// writes a structured Cloud Logging entry. When the Platform API v1 event
// bus ships, the body re-points to the platform client. Call sites do not
// change.
//
// Function signature is the contract per pattern §2.1:
//
//   publishEvent(
//     { eventType, payload, tenantId, clientId, actorUid, occurredAt },
//     options?: { mirrorToFirestore?: boolean }
//   ): Promise<void>
//
// The publisher does NOT:
//   - implement retry (Cloud Logging's own delivery semantics suffice)
//   - act as an audit log (apiLogs middleware is its own thing)
//   - notify users (events notify systems)
// =============================================================================

import { randomUUID } from 'node:crypto';

// ─── Types ──────────────────────────────────────────────────────────────────

/**
 * The canonical platform event envelope, per Event Publisher Pattern §4.
 * Every event written by this publisher conforms to this shape regardless
 * of transport.
 */
export interface AngsanaEventEnvelope {
  /** UUID v4, generated by the publisher at emit time. */
  eventId: string;
  /** `<entity>.<verb>` per §5 vocabulary; or `<domain>.<entity>.<verb>` per §5.2. */
  eventType: string;
  /** Semver of the payload schema for this event type. Starts at "1.0". */
  eventVersion: string;
  /** Required on all events. Cross-tenant events are not supported. */
  tenantId: string;
  /** Null for tenant-level events. */
  clientId: string | null;
  /** ISO 8601 timestamp of when the underlying state change happened. */
  occurredAt: string;
  /** UID of the user/service responsible. Null for system-originated. */
  actorUid: string | null;
  /** Event-type-specific payload. Schema governed by eventType + eventVersion. */
  payload: Record<string, unknown>;
  /** Origin metadata. */
  source: {
    component: string;
    environment: string;
  };
}

/**
 * Inputs the caller supplies. The publisher fills in eventId, eventVersion,
 * and source.
 */
export interface PublishEventInput {
  /** Canonical event type, e.g. "wishlist.added", "migration.completed". */
  eventType: string;
  /** Event-type-specific payload. */
  payload: Record<string, unknown>;
  /** Tenant the event belongs to. Required. */
  tenantId: string;
  /** Client scope, or null for tenant-level events. */
  clientId: string | null;
  /** UID of the actor, or null for system-originated. */
  actorUid: string | null;
  /** ISO 8601 timestamp of the underlying state change. */
  occurredAt: string;
  /**
   * Override eventVersion (defaults to "1.0"). Increment when a payload
   * schema changes for a given eventType.
   */
  eventVersion?: string;
}

export interface PublishEventOptions {
  /**
   * Per Event Publisher Pattern §3, an optional Firestore append at
   * tenants/{tenantId}/events/{autoId} with a 30-day TTL. Default false;
   * stays off for the Wishlists slice. Exists for forward compatibility.
   */
  mirrorToFirestore?: boolean;
}

// ─── Configuration ──────────────────────────────────────────────────────────

const COMPONENT_NAME = 'exchange-app';

function getEnvironmentName(): string {
  // Cloud Run convention: K_SERVICE / K_REVISION. Fall back to NODE_ENV.
  return (
    process.env.ANGSANA_ENV ||
    process.env.K_REVISION ||
    process.env.NODE_ENV ||
    'unknown'
  );
}

// ─── Validation ─────────────────────────────────────────────────────────────

const ISO_8601_RE =
  /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/;

/**
 * Loose check: format is `<entity>.<verb>` or `<domain>.<entity>.<verb>`.
 * The verb vocabulary itself is enforced by convention at call sites; the
 * publisher only enforces the shape.
 */
const EVENT_TYPE_RE = /^[a-z][a-zA-Z0-9]*(\.[a-z][a-zA-Z0-9]*){1,2}$/;

function validate(input: PublishEventInput): void {
  if (!input.tenantId || typeof input.tenantId !== 'string') {
    throw new Error('publishEvent: tenantId is required');
  }
  if (!input.eventType || !EVENT_TYPE_RE.test(input.eventType)) {
    throw new Error(
      `publishEvent: eventType "${input.eventType}" does not match <entity>.<verb> shape`
    );
  }
  if (!input.occurredAt || !ISO_8601_RE.test(input.occurredAt)) {
    throw new Error(
      `publishEvent: occurredAt "${input.occurredAt}" is not a valid ISO 8601 timestamp`
    );
  }
  if (input.payload && typeof input.payload !== 'object') {
    throw new Error('publishEvent: payload must be an object');
  }
}

// ─── Severity ───────────────────────────────────────────────────────────────

/**
 * Per Event Publisher Pattern §4.1, severity is INFO by default, ERROR for
 * events that represent error conditions (e.g. migration failures).
 */
function severityFor(eventType: string): 'INFO' | 'ERROR' {
  if (eventType === 'migration.failed') return 'ERROR';
  // Generic .failed verb (forward-compat for future error events).
  if (eventType.endsWith('.failed')) return 'ERROR';
  return 'INFO';
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Emit an event through the publisher-lite.
 *
 * Today the body writes to Cloud Logging via console; when the platform
 * event bus ships, this body re-points and call sites do not change.
 *
 * @example
 * await publishEvent({
 *   eventType: 'wishlist.added',
 *   payload: { wishlistId, addedBy, source: 'client-request' },
 *   tenantId: 'angsana',
 *   clientId: 'cegid-spain',
 *   actorUid: ctx.uid,
 *   occurredAt: new Date().toISOString(),
 * });
 */
export async function publishEvent(
  input: PublishEventInput,
  options: PublishEventOptions = {}
): Promise<void> {
  validate(input);

  const envelope: AngsanaEventEnvelope = {
    eventId: randomUUID(),
    eventType: input.eventType,
    eventVersion: input.eventVersion ?? '1.0',
    tenantId: input.tenantId,
    clientId: input.clientId,
    occurredAt: input.occurredAt,
    actorUid: input.actorUid,
    payload: input.payload ?? {},
    source: {
      component: COMPONENT_NAME,
      environment: getEnvironmentName(),
    },
  };

  // ── Cloud Logging serialisation (default transport) ────────────────────
  // Per pattern §4.1: structured JSON under top-level key `angsanaEvent`,
  // severity INFO/ERROR. Cloud Logging captures `severity` from the
  // structured payload when written via console.
  const severity = severityFor(input.eventType);
  const entry = { severity, angsanaEvent: envelope };

  if (severity === 'ERROR') {
    // eslint-disable-next-line no-console
    console.error(JSON.stringify(entry));
  } else {
    // eslint-disable-next-line no-console
    console.log(JSON.stringify(entry));
  }

  // ── Optional Firestore mirror ──────────────────────────────────────────
  // Per pattern §3, off by default and stays off for the Wishlists slice.
  // The hook is here so future components can opt in without changing
  // call sites. Implementation is intentionally deferred until a consumer
  // requests it (the consumer model itself is settled at that point per
  // pattern §7).
  if (options.mirrorToFirestore) {
    // Forward-compatibility hook. No-op for now.
    // When enabled, this would append to tenants/{tenantId}/events/{autoId}
    // with a 30-day TTL. Deliberately unimplemented for this slice.
  }
}
