// =============================================================================
// Angsana Exchange — Event Publisher (publisher-lite)
//
// Implements the Angsana Event Publisher Pattern v0.1 (in-tree mirror at
// docs/architecture/Angsana_Event_Publisher_Pattern_v0_1.md). This is the
// single re-point site for event emission from Exchange. Today the body
// writes a structured Cloud Logging entry. When the Platform API v1 event
// bus ships, the body re-points to the platform client. Call sites do not
// change.
//
// Function signature is the contract per pattern §2.1:
//
//   publishEvent(
//     { eventType, payload, tenantId, clientId, actorUid, occurredAt },
//     options?: { mirrorToFirestore?: boolean }
//   ): Promise<void>
//
// The publisher does NOT:
//   - implement retry (Cloud Logging's own delivery semantics suffice)
//   - act as an audit log (apiLogs middleware is its own thing)
//   - notify users (events notify systems)
// =============================================================================

import { randomUUID } from 'node:crypto';
import { adminDb } from '@/lib/firebase/admin';
import { Timestamp } from 'firebase-admin/firestore';

// ─── Types ──────────────────────────────────────────────────────────────────

/**
 * The canonical platform event envelope, per Event Publisher Pattern §4.
 * Every event written by this publisher conforms to this shape regardless
 * of transport.
 */
export interface AngsanaEventEnvelope {
  /** UUID v4, generated by the publisher at emit time. */
  eventId: string;
  /** `<entity>.<verb>` per §5 vocabulary; or `<domain>.<entity>.<verb>` per §5.2. */
  eventType: string;
  /** Semver of the payload schema for this event type. Starts at "1.0". */
  eventVersion: string;
  /** Required on all events. Cross-tenant events are not supported. */
  tenantId: string;
  /** Null for tenant-level events. */
  clientId: string | null;
  /** ISO 8601 timestamp of when the underlying state change happened. */
  occurredAt: string;
  /** UID of the user/service responsible. Null for system-originated. */
  actorUid: string | null;
  /** Event-type-specific payload. Schema governed by eventType + eventVersion. */
  payload: Record<string, unknown>;
  /** Origin metadata. */
  source: {
    component: string;
    environment: string;
  };
}

/**
 * Inputs the caller supplies. The publisher fills in eventId, eventVersion,
 * and source.
 */
export interface PublishEventInput {
  /** Canonical event type, e.g. "wishlist.added", "migration.completed". */
  eventType: string;
  /** Event-type-specific payload. */
  payload: Record<string, unknown>;
  /** Tenant the event belongs to. Required. */
  tenantId: string;
  /** Client scope, or null for tenant-level events. */
  clientId: string | null;
  /** UID of the actor, or null for system-originated. */
  actorUid: string | null;
  /** ISO 8601 timestamp of the underlying state change. */
  occurredAt: string;
  /**
   * Override eventVersion (defaults to "1.0"). Increment when a payload
   * schema changes for a given eventType.
   */
  eventVersion?: string;
}

export interface PublishEventOptions {
  /**
   * Per Event Publisher Pattern §3, an optional Firestore append at
   * tenants/{tenantId}/events/{autoId} with a 30-day TTL. Default false;
   * stays off for the Wishlists slice. Exists for forward compatibility.
   */
  mirrorToFirestore?: boolean;
}

// ─── Configuration ──────────────────────────────────────────────────────────

const COMPONENT_NAME = 'exchange-app';

/**
 * Per S3-pre-code Decision #8: always-on Firestore mirror for the v0.1
 * substantive-edit verbs (linked-edit category, Spec §4.2). The mirror
 * writes a canonical PlatformEvent shape to
 * `tenants/{tenantId}/platformEvents/{eventId}` so Core's existing
 * `processTenantEvent` Firestore trigger (HANDLER_MAP-routed) processes
 * the event. Other verbs remain Cloud-Logging-only unless an opt-in
 * `mirrorToFirestore: true` is supplied at the call site (forward-compat).
 *
 * Adding to this list:
 *   1. Register the verb in
 *      `angsana-core-prod-project/functions/src/config/eventRegistry.json`
 *      with the appropriate handler key.
 *   2. Add the verb here.
 *   3. Land both repo changes in the same phase to avoid orphaned
 *      Firestore docs in pending state.
 */
const FIRESTORE_MIRROR_WHITELIST: ReadonlySet<string> = new Set([
  // §4.2 Wishlist substantive edits
  'wishlist.added',
  'wishlist.archived',
  'wishlist.targetingHintsChanged',
  'wishlist.websiteChanged',
  // §4.2 Campaign substantive edits
  'campaign.added',
  'campaign.statusChanged',
  'campaign.nameChanged',
  'campaign.targetingHintsChanged',
]);

/**
 * Default retention for mirrored events. Mirrors Core's
 * `WORK_ITEM_DEFAULT_RETENTION_DAYS` (60 days) + 'processing' category
 * default. The mirror's TTL field uses Firestore's existing TTL policy on
 * the `platformEvents` collection.
 */
const MIRROR_RETENTION_DAYS = 60;
const MS_PER_DAY = 24 * 60 * 60 * 1000;


function getEnvironmentName(): string {
  // Cloud Run convention: K_SERVICE / K_REVISION. Fall back to NODE_ENV.
  return (
    process.env.ANGSANA_ENV ||
    process.env.K_REVISION ||
    process.env.NODE_ENV ||
    'unknown'
  );
}

// ─── Validation ─────────────────────────────────────────────────────────────

const ISO_8601_RE =
  /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/;

/**
 * Loose check: format is `<entity>.<verb>` or `<domain>.<entity>.<verb>`.
 * The verb vocabulary itself is enforced by convention at call sites; the
 * publisher only enforces the shape.
 */
const EVENT_TYPE_RE = /^[a-z][a-zA-Z0-9]*(\.[a-z][a-zA-Z0-9]*){1,2}$/;

function validate(input: PublishEventInput): void {
  if (!input.tenantId || typeof input.tenantId !== 'string') {
    throw new Error('publishEvent: tenantId is required');
  }
  if (!input.eventType || !EVENT_TYPE_RE.test(input.eventType)) {
    throw new Error(
      `publishEvent: eventType "${input.eventType}" does not match <entity>.<verb> shape`
    );
  }
  if (!input.occurredAt || !ISO_8601_RE.test(input.occurredAt)) {
    throw new Error(
      `publishEvent: occurredAt "${input.occurredAt}" is not a valid ISO 8601 timestamp`
    );
  }
  if (input.payload && typeof input.payload !== 'object') {
    throw new Error('publishEvent: payload must be an object');
  }
}

// ─── Severity ───────────────────────────────────────────────────────────────

/**
 * Per Event Publisher Pattern §4.1, severity is INFO by default, ERROR for
 * events that represent error conditions (e.g. migration failures).
 */
function severityFor(eventType: string): 'INFO' | 'ERROR' {
  if (eventType === 'migration.failed') return 'ERROR';
  // Generic .failed verb (forward-compat for future error events).
  if (eventType.endsWith('.failed')) return 'ERROR';
  return 'INFO';
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Emit an event through the publisher-lite.
 *
 * Today the body writes to Cloud Logging via console; when the platform
 * event bus ships, this body re-points and call sites do not change.
 *
 * @example
 * await publishEvent({
 *   eventType: 'wishlist.added',
 *   payload: { wishlistId, addedBy, source: 'client-request' },
 *   tenantId: 'angsana',
 *   clientId: 'cegid-spain',
 *   actorUid: ctx.uid,
 *   occurredAt: new Date().toISOString(),
 * });
 */
export async function publishEvent(
  input: PublishEventInput,
  options: PublishEventOptions = {}
): Promise<void> {
  validate(input);

  const envelope: AngsanaEventEnvelope = {
    eventId: randomUUID(),
    eventType: input.eventType,
    eventVersion: input.eventVersion ?? '1.0',
    tenantId: input.tenantId,
    clientId: input.clientId,
    occurredAt: input.occurredAt,
    actorUid: input.actorUid,
    payload: input.payload ?? {},
    source: {
      component: COMPONENT_NAME,
      environment: getEnvironmentName(),
    },
  };

  // ── Cloud Logging serialisation (default transport) ────────────────────
  // Per pattern §4.1: structured JSON under top-level key `angsanaEvent`,
  // severity INFO/ERROR. Cloud Logging captures `severity` from the
  // structured payload when written via console.
  const severity = severityFor(input.eventType);
  const entry = { severity, angsanaEvent: envelope };

  if (severity === 'ERROR') {
    console.error(JSON.stringify(entry));
  } else {
    console.log(JSON.stringify(entry));
  }

  // ── Firestore mirror ───────────────────────────────────────────────────
  // Per S3-pre-code Decision #8: an always-on whitelist mirror writes the
  // canonical PlatformEvent shape to
  // `tenants/{tenantId}/platformEvents/{eventId}`. Core's existing
  // `processTenantEvent` Firestore trigger picks the doc up and routes it
  // through HANDLER_MAP (notifications/linkedEditEvent for the v0.1
  // substantive-edit verbs).
  //
  // The explicit `options.mirrorToFirestore=true` opt-in path is
  // preserved as a per-call override for non-whitelisted verbs (e.g.
  // `reseed.completed` if a future caller wants observability without
  // touching the whitelist).
  //
  // Per pattern §8.3 (notifications fan-out) — mirror failures are
  // non-fatal to the publisher: Cloud Logging already captured the
  // event, and the Core fan-out is observability rather than a hard
  // requirement of the calling business logic. We surface failures via
  // a console.error so they're visible in Cloud Logs.
  const shouldMirror =
    FIRESTORE_MIRROR_WHITELIST.has(input.eventType) ||
    options.mirrorToFirestore === true;

  if (shouldMirror) {
    try {
      await writeFirestoreMirror(envelope);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(
        JSON.stringify({
          severity: 'WARNING',
          message: 'publishEvent: Firestore mirror failed (non-fatal)',
          eventId: envelope.eventId,
          eventType: envelope.eventType,
          tenantId: envelope.tenantId,
          error: message,
        })
      );
    }
  }
}

// ─── Firestore mirror ───────────────────────────────────────────────────────

/**
 * Write the canonical PlatformEvent doc to
 * `tenants/{tenantId}/platformEvents/{eventId}`. Shape mirrors what Core's
 * `lib/events/types.ts::PlatformEvent` expects (the same shape Core writes
 * for its own `workitem.*` events via `lib/workItems/eventEmissions.ts`).
 *
 * The doc is `status: 'pending'` so Core's `processTenantEvent` trigger
 * will pick it up and route via HANDLER_MAP. `attemptCount: 0`,
 * `maxAttempts: 3` — Core overrides on first attempt anyway. `expiresAt`
 * is the Firestore TTL field (60 days) per Core's existing convention.
 */
async function writeFirestoreMirror(
  envelope: AngsanaEventEnvelope
): Promise<void> {
  const now = Timestamp.fromMillis(Date.now());
  const expiresAt = Timestamp.fromMillis(
    Date.now() + MIRROR_RETENTION_DAYS * MS_PER_DAY
  );

  // Shape conforms to Core's PlatformEvent (lib/events/types.ts) so the
  // existing processEventDoc trigger in Core can process the doc without
  // any shape adapter. Field names are exact matches.
  const platformEvent: Record<string, unknown> = {
    id: envelope.eventId,
    eventType: envelope.eventType,
    tenantId: envelope.tenantId,
    source: envelope.source.component, // e.g. 'exchange-app'
    surface: 'exchange',
    service: deriveService(envelope.eventType),
    operation: deriveOperation(envelope.eventType),
    action: envelope.eventType,
    resourceTypes: deriveResourceTypes(envelope.eventType),
    env: envelope.source.environment,
    actor: envelope.actorUid,
    payload: envelope.payload,
    // Scope: tenant-platform for substantive-edit linked-record events.
    // (clientId-scoped events are valid too — the registry's `scope` field
    // settles routing on the Core side. Tenant-platform is the safe
    // default for these verbs.)
    scope: 'tenant-platform',
    category: 'processing',
    schemaVersion: 1,
    eventVersion: parseFloat(envelope.eventVersion) || 1,
    sensitivity: 'moderate',
    status: 'pending',
    attemptCount: 0,
    maxAttempts: 3,
    retentionDays: MIRROR_RETENTION_DAYS,
    expiresAt,
    createdAt: now,
    updatedAt: now,
  };

  if (envelope.clientId) {
    platformEvent.clientId = envelope.clientId;
  }

  await adminDb
    .collection('tenants')
    .doc(envelope.tenantId)
    .collection('platformEvents')
    .doc(envelope.eventId)
    .set(platformEvent);
}

/**
 * Derive the `service` field from the eventType prefix. Convention mirrors
 * Core's emitter conventions (lib/workItems/eventEmissions.ts uses
 * `service: 'workItems'`). For Exchange-emitted events the prefix is the
 * domain entity (wishlist / campaign / reseed / migration).
 */
function deriveService(eventType: string): string {
  const dot = eventType.indexOf('.');
  return dot > 0 ? eventType.slice(0, dot) : 'exchange';
}

/**
 * Derive the `operation` field from the eventType suffix
 * (e.g. `wishlist.added` → `'added'`).
 */
function deriveOperation(eventType: string): string {
  const dot = eventType.indexOf('.');
  return dot >= 0 ? eventType.slice(dot + 1) : eventType;
}

/**
 * Derive the `resourceTypes` array. Mirrors the Core convention of
 * `[domain, specific-resource]` (e.g. workItems uses
 * `['workItem', workItemType]`). For Exchange's linked-record events
 * the singular entity name is the canonical resource type.
 */
function deriveResourceTypes(eventType: string): string[] {
  const service = deriveService(eventType);
  return [service];
}

